lib/esad_web/router.ex
defmodule EsadWeb.Router do
  use EsadWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EsadWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/streams", StreamController, :list
    get "/streams/:stream", StreamController, :stream
  end

  # Other scopes may use custom stacks.
  # scope "/api", EsadWeb do
  #   pipe_through :api
  # end
end

lib/esad/application.ex
defmodule Esad.Application do
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      EsadWeb.Endpoint,
      {Esad.HttpPollerEndpoint, interval: 60},
      {Phoenix.PubSub, [name: Esad.PubSub, adapter: Phoenix.PubSub.PG2]}
    ]

    opts = [strategy: :one_for_one, name: Esad.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EsadWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/esad/event.ex
defmodule Esad.Event do
  @moduledoc """
  Represent a event for a specific point of time

  """

  defstruct stream: nil, datetime: nil, value: nil, tags: nil
end

lib/esad/event_stream.ex
defmodule Esad.EventStream do
  @moduledoc """
  Consume a stream of event and do some analytics

  The event stream should manage multiple "logical" streams
  which can be idenitifed by it's source. The source can be
  a unique identifier for a remote endpoint or an internal
  reference.

  Speficially it's required that the input for each individual
  source is processed in order, it should be able to detect the
  below conditions for any given source and should be able to
  produce minimal metrics for

  * Value differs by more than ±40%
  * Value above/below threshold for `n` periods

  For any source that has not received any data for a configurable
  time period it's state should be removed.
  """

  @doc """
  Process the incoming event for a particular source.

  If the source does not exist it should be created automatically
  """
  def input(%Esad.Event{} = _ev) do
    raise RuntimeError, message: "not implemented"
  end


  @doc """
  Retrieve metrics for the given source

  Returns data in the form:

  %StreamState{
    outputs: [....],
    inputs: [...],
    hourly_error_rate: ...
  }

  Should raise an error if metric is not found.
  """
  def metric!(_stream), do: raise RuntimeError, message: "not implemented"


  @doc """
  Stop the given stream
  """
  def stop(_stream), do: raise RuntimeError, message: "not implemeted"
end

lib/esad/http_poller_endpoint.ex
defmodule Esad.HttpPollerEndpoint do
  @moduledoc """
  Get value from remote endpoint on a fixed interval
  """

  use GenServer

  require Logger

  def start_link(opts) do
    {name, arg} = Keyword.pop(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, arg, name: name)
  end


  @doc """
  Trigger an immediate poll of the remote endpoint
  """
  def poll(pid), do: GenServer.cast(pid, :poll)

  @impl true
  def init(cfg) do
    {initial_state, cfg} = Keyword.pop(cfg, :state)
    {interval, _cfg} = Keyword.pop(cfg, :interval)


    {:ok, tref} = :timer.send_interval(interval * 1000, :poll)

    Logger.info("Starting http poller with interval := #{interval}s")

    {:ok,
     %{
       timer: tref,
       state: initial_state
     }}
  end

  @impl true
  def handle_cast(:poll, state) do
    next_state = on_interval(state)
    {:noreply, next_state}
  end

  @impl true
  def handle_info(:poll, state) do
    next_state = on_interval(state)
    {:noreply, next_state}
  end


  defp on_interval(state) do
    {endpoint, body} = Application.get_env(:esad, __MODULE__)[:endpoint]

    requested = DateTime.utc_now()

    # poll the API
    headers = [{"content-type", "application/x-www-form-urlencoded"}]

    %{status_code: 200, body: body} = HTTPoison.post! endpoint, body, headers

    ev = %Esad.Event{
      stream: "#{__MODULE__}",
      datetime: requested,
      value: String.to_integer(body)
    }

    Logger.info "Received #{inspect ev}"

    :ok = Esad.EventStream.input(ev)

    state
  end



end

lib/esad_web/controllers/page_controller.ex
defmodule EsadWeb.PageController do
  use EsadWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/esad_web/controllers/stream_controller.ex
defmodule EsadWeb.StreamController do
  use EsadWeb, :controller

  alias Esad.Event

  def list(conn, _params) do
    render(conn, "index.html", streams: streams())
  end


  def stream(conn, %{"stream" => stream_id}) do
    stream = streams()[stream_id]
    render(conn, "stream.html", stream_id: stream_id, stream: stream)
  end


  defp streams() do
    stat = File.stat!(__ENV__.file)
    gsec = :calendar.datetime_to_gregorian_seconds(stat.ctime)
    datetime = DateTime.from_gregorian_seconds(gsec)
    ev2 = %Event{stream: "example-2", datetime: datetime}

      %{
        "example-1" => %{
            outputs: [],
            inputs: [],
            stats: %{
              hourly_error_rate: 0,
              inputs: 321,
              outputs: 0
            }
          },

        "example-2" => %{
            outputs: [%{ev2|value: "3 errors in a row", tags: ["error"]}],
            inputs: [],
            stats: %{
              hourly_error_rate: 1,
              inputs: 3,
              outputs: 1
            }
          },
        }
  end
end

lib/esad_web/views/error_view.ex
defmodule EsadWeb.ErrorView do
  use EsadWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/esad_web/views/layout_view.ex
defmodule EsadWeb.LayoutView do
  use EsadWeb, :view
end

lib/esad_web/views/page_view.ex
defmodule EsadWeb.PageView do
  use EsadWeb, :view
end

lib/esad_web/views/stream_view.ex
defmodule EsadWeb.StreamView do
  use EsadWeb, :view
end

lib/esad_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Esad · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Index", to: Routes.page_path(@conn, :index) %></li>
            <li><%= link "Streams", to: Routes.stream_path(@conn, :list) %></li>

          </ul>
        </nav>
        <b>Elixir Signal Analamolies Detector</b>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/esad_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1>Signal Analamolies Detection System</h1>
  <p>A simple way to see analamolies in .</p>
</section>

lib/esad_web/templates/stream/index.html.eex
<section class="phx-hero">
  <h1>Signal Analamolies Detection System</h1>
  <p>A simple way to see analamolies in .</p>
</section>

<section class="row">
  <article class="column">
    <h2>Streams</h2>
    <ul>
    <%= for {id, state} <- @streams do %>
      <li><%= link id, to: Routes.stream_path(@conn, :stream, id) %></li>
    <% end %>
  </article>
  <article class="column">
    <h2>Stats</h2>
    <ul>
      <li>Total Streams: <%= map_size(@streams) %></li>
      <li>Total Input Events: <%= Enum.reduce(@streams, 0, fn({_, v}, acc) -> v.stats.inputs + acc end) %></li>
      <li>Total Output Events: <%= Enum.reduce(@streams, 0, fn({_, v}, acc) -> v.stats.outputs + acc end) %></li>
      <li>Errors pr. hour: <%= Enum.reduce(@streams, 0, fn({_, v}, acc) -> v.stats.hourly_error_rate + acc end) %></li>
    </ul>
  </article>
</section>

lib/esad_web/templates/stream/stream.html.eex
<section class="phx-hero">
  <h1>Stream: <%= @stream_id %></h1>
</section>

<pre><%= inspect @stream, pretty: true %></pre>